name: CI - Testes e Lint

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar ESLint
        run: npm run lint

      - name: Criar pasta de relatórios
        run: mkdir -p reports

      - name: Rodar testes
        run: |
          mkdir -p reports
          npm test

      - name: Verificar arquivos gerados
        run: ls -R reports

      - name: Upload relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/